from pydantic import BaseModel, Field
from typing import List, Dict
import hashlib
import json

class CandidateDispatch(BaseModel):
    """
    Represents a candidate dispatch proposal generated by the stability solver,
    which will be simulated by GridGate.
    """
    negotiation_id: str = Field(..., description="Unique ID for this clearing interval")
    coalition: List[str] = Field(..., description="List of microgrid IDs in the coalition")
    p_setpoints_kw: Dict[str, float] = Field(..., description="Active power setpoints for each agent (negative = load, positive = gen)")
    q_setpoints_kvar: Dict[str, float] = Field(default_factory=dict, description="Reactive power setpoints")
    
def hash_dispatch(dispatch: CandidateDispatch) -> str:
    """
    Produces a canonical RFC-8785 style hash of the CandidateDispatch.
    This hash must exactly match the on-chain Settlement verification.
    """
    payload = {
        "coalition": sorted(dispatch.coalition),
        "negotiation_id": dispatch.negotiation_id,
        "p_setpoints_kw": {
            k: round(float(v), 6) for k, v in sorted(dispatch.p_setpoints_kw.items())
        },
        "q_setpoints_kvar": {
            k: round(float(v), 6) for k, v in sorted(dispatch.q_setpoints_kvar.items())
        }
    }
    canonical = json.dumps(payload, sort_keys=True, separators=(",", ":"))
    return hashlib.sha256(canonical.encode("utf-8")).hexdigest()
